# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



def even_fib_sum(limit)
	sum = 0
	second = 1
	first = 1
	nth = second + first
	while nth <= limit
		sum += nth if nth % 2 == 0
		second = first
		first = nth
		nth = first + second
	end
	return sum
end

puts even_fib_sum(4000000)
